{% set name = "pyunigps" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyunigps-{{ version }}.tar.gz
  sha256: 8616ed8aac200854cbaa91e829321d7f58f26ab7265af506afa763d12c244f07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pynmeagps >=1.1.0
    - pyrtcm >=1.1.10

test:
  imports:
    - pyunigps
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/semuconsulting/pyunigps
  description: Python library for parsing and generating Unicore UNI GNSS protocol messages.
  summary: Unicore protocol parser and generator
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyunigps
  dev_url: https://github.com/semuconsulting/pyunigps
extra:
  recipe-maintainers:
    - semuadmin
